# Copyright (C) 2021-2023 Ye Xu, Xin Zhang, Chongpeng Huang, Xiaorong Qiu

import run_cnn_15S, run_cnn_TFF, run_cnn_COV, run_cnn_MIT, run_cnn_NWP, run_cnn_CAL

# run_cnn_15S.by_resnext50_part(num_epochs=30)
run_cnn_15S.by_resnext50_all(num_epochs=50)
# run_cnn_15S.by_vgg16bn_all(num_epochs=50)
# run_cnn_15S.by_vgg16bn_part(num_epochs=30)
# run_cnn_15S.by_swinb_all(num_epochs=50)
# run_cnn_15S.by_swinb_part(num_epochs=30)
# run_cnn_TFF.by_swinb_part(num_epochs=30)
# run_cnn_TFF.by_swinb_all(num_epochs=50)
# run_cnn_COV.by_swinb_part(num_epochs=30)
# run_cnn_COV.by_swinb_all(num_epochs=50)
# run_cnn_NWP.by_swinb_part(num_epochs=30)
# run_cnn_NWP.by_swinb_all(num_epochs=50)
# run_cnn_MIT.by_swinb_part(num_epochs=30)
# run_cnn_MIT.by_swinb_all(num_epochs=50)
# run_cnn_CAL.by_swinb_part(num_epochs=30)
# run_cnn_CAL.by_swinb_all(num_epochs=50)
# run_cnn_TFF.by_resnext50_all(num_epochs=50)
# run_cnn_TFF.by_resnext50_part(num_epochs=30)
# run_cnn_TFF.by_vgg16bn_all(num_epochs=50)
# run_cnn_TFF.by_vgg16bn_part(num_epochs=30))
# run_cnn_UIUC.by_resnext50_all(num_epochs=50)
# run_cnn_UIUC.by_resnext50_part(num_epochs=30)
# run_cnn_UIUC.by_vgg16bn_all(num_epochs=50)
# run_cnn_UIUC.by_vgg16bn_part(num_epochs=30)
# run_cnn_COV.by_resnext50_all(num_epochs=50)
# run_cnn_COV.by_resnext50_part(num_epochs=30)
# run_cnn_COV.by_vgg16bn_all(num_epochs=50)
# run_cnn_COV.by_vgg16bn_part(num_epochs=30)
# run_cnn_MIT.by_resnext50_all(num_epochs=50)
# run_cnn_MIT.by_resnext50_part(num_epochs=30)
# run_cnn_MIT.by_vgg16bn_all(num_epochs=50)
# run_cnn_MIT.by_vgg16bn_part(num_epochs=30)
# run_cnn_CAL.by_vgg16bn_all(num_epochs=50)
# run_cnn_CAL.by_vgg16bn_part(num_epochs=30)
# run_cnn_NWP.by_resnext50_part(num_epochs=30)
# run_cnn_NWP.by_resnext50_all(num_epochs=50)
# run_cnn_NWP.by_vgg16bn_all(num_epochs=50)
# run_cnn_NWP.by_vgg16bn_part(num_epochs=30)
# run_cnn_CAL.by_resnext50_all(num_epochs=50)
# run_cnn_CAL.by_resnext50_part(num_epochs=30)
# run_cnn_CAL.by_vgg16bn_part(num_epochs=30)
# run_cnn_CAL.by_vgg16bn_all(num_epochs=50)